### ISSUE TITLE
[Civ Name] is up for sale, [Civ Name] days until the civ is deleted!

### ISSUE THREAD

**Issue by TwilightVanish** [ataranlen/civcraft#105]
Civs in debt will start the countdown to be deleted but when it reaches 0 days it wont be deleted.
Examples:
![](https://i.gyazo.com/b877cfcc594de48c12ef2c7583f3c70d.png)

![](https://i.gyazo.com/3a3bd9b0e4bbf5abc5f5fa363ebcf585.png)

**Comment by YourCoal** [comment]
I found the issue in a localization error, I can't edit on my phone so I will try when I get home to fix it.

**Comment by YourCoal** [comment]
Okay I figured it how to edit on my phone, a pull request has been made. #106
