### ISSUE TITLE
After port an error with NBTTag

### ISSUE THREAD

**Issue by CivkaError** [ataranlen/civcraft#107]
http://paste.xtrafrancyz.net/0s2TvOv.sql
What i need do? :(

**Comment by BenjaminGoGurts** [comment]
Maybe update/downgrade your plugins lol

**Comment by ataranlen** [comment]
Civcraft v1.6.4 is not compatible with Minecraft 1.6.4.

Also, Civcraft v1.6.4 is no longer supported.
