### ISSUE TITLE
Rivendell - camp not set as spawn

### ISSUE THREAD

**Issue by mummabia** [ataranlen/civcraft#114]
Hi, I have a camp.  Every time I die I end up at spawn.  I've used the /sethome command and it says that "Home is set to the current location" and the /home works fine.  But on death, I go back to spawn.  Any ideas?  Thanks.

**Comment by BenjaminGoGurts** [comment]
It's because on the main server it was coded that you respawn at your camp. On MineTexas you always respawn at spawn and you have to do /home to get back to your camp.
