### ISSUE TITLE
Quarry dupe

### ISSUE THREAD

**Issue by TheLegionCrazy** [ataranlen/civcraft#116]
Hello dear Ataranlen. Need a little help, if you're not busy. I copied the quarry as there was dupe in it. I can not understand why it does not remove the pickaxes, although their durability is spelled out.
I tryied fix it with deleting remove/add actions, but it works, but while stack has 1 dura it not deleting, but adding resources to chest
`if (damage < 131) {
                        if (stack.getDurability() >= 2) {
                            stack.setDurability(damage);
                        } else {
                            try {
                                this.updateInventory(Action.REMOVE, source_inv, stack);
                            } catch (InterruptedException e) {
                                return;
                            }
                        }
                    }`

**Comment by TheLegionCrazy** [comment]
Oh, quarry duping pickaxes when u press to item to fast

**Comment by TheLegionCrazy** [comment]
i fixed it

**Comment by ataranlen** [comment]
Fixed it how?

**Comment by TheLegionCrazy** [comment]
#118 look this please
@ataranlen, try not remove stack, but while stack's dura under or 0 remove it
stack.setDurability(damage); in ur code

https://gyazo.com/aadfabc0433260f571c2dd938eab91c8
