### ISSUE TITLE
Revolution is impossible

### ISSUE THREAD

**Issue by TwilightVanish** [ataranlen/civcraft#117]
![image](https://cloud.githubusercontent.com/assets/18649720/25841482/9840ca94-34a0-11e7-8a3b-dff1bc795710.png)

I am unable to stage a revolution, no matter how much money I have.

**Comment by BenjaminGoGurts** [comment]
True putting or in your town

**Comment by ataranlen** [comment]
The money must be in the town, not in the player's holdings.
