### ISSUE TITLE
Some blocks after demolishing not deleting

### ISSUE THREAD

**Issue by TheLegionCrazy** [ataranlen/civcraft#126]
im going to fix this issue

**Comment by ataranlen** [comment]
This video contains content from UMG_MK, who has blocked it in your country on copyright grounds.

**Comment by ataranlen** [comment]
You must give a description for the issue. A youtube video is not sufficient.

https://coenjacobs.me/2013/12/06/effective-bug-reports-on-github/

**Comment by TheLegionCrazy** [comment]
So, when u placing sugar_cane and u building the structure on that blocks (monument on video) and demolishing the strucutre - structure blocks are fine and not deleted from method onBuildUndo (sugar cane and redstone can't import to undo file)

**Comment by ataranlen** [comment]
It replaces them with Air, yes?

**Comment by TheLegionCrazy** [comment]
not replacing, they are fine (it works on official repository (not only on my fork))

**Comment by ataranlen** [comment]
Can you explain the steps to reproduce, The expected result, and the actual result?

**Comment by TheLegionCrazy** [comment]
it works on official repository (not only on my fork) 

gif : http://imgur.com/a/aoktg

fix : #127
