### ISSUE TITLE
Change readme.md?

### ISSUE THREAD

**Issue by TheLegionCrazy** [ataranlen/civcraft#128]
civilizationcraft.net is closed and reopened to civ-war.com on shotbow.net

**Comment by ataranlen** [comment]
The community at civ-war.com has not contributed to this project.

**Comment by TheLegionCrazy** [comment]
but civilizationcraft.net closed
maybe atlas.civcraft.net?

**Comment by ataranlen** [comment]
The domain has not expired. If and when it expires, I will remove the link. Till then, Archive views from google can show the site.

**Comment by TheLegionCrazy** [comment]
kk
