### ISSUE TITLE
Error placing camps and using commands

### ISSUE THREAD

**Issue by KarlEU4** [ataranlen/civcraft#133]
Just what the title said
[latest.txt](https://github.com/ataranlen/civcraft/files/1286234/latest.txt)

Here are the logs

**Comment by SuperRyan6000** [comment]
accidently posted

Here are the logs


[latest.txt](https://github.com/ataranlen/civcraft/files/1286234/latest.txt)

not exactly sure how to post files so if it doesnt work contact me sorry if im in school and cant respond immeadietly

**Comment by ataranlen** [comment]
You are missing the Lib folder (server_root)/plugins/Civcraft/lib

You need to follow the ReadMe.txt included in the zip/7z download and copy the folders as explained there.
