### ISSUE TITLE
Since barracks got rebuilt settler's cost going to 25000 every time

### ISSUE THREAD

**Issue by TheLegionCrazy** [ataranlen/civcraft#134]
w8, going fix it

**Comment by ataranlen** [comment]
Is it specifically on rebuild? I'm unable to reproduce this issue.

**Comment by ataranlen** [comment]
Original Barracks
![2017-12-21_19 04 35](https://user-images.githubusercontent.com/1933566/34281072-ccc0306e-e681-11e7-92af-da3ee6707bc1.png)

Destroy:
![2017-12-21_19 05 00](https://user-images.githubusercontent.com/1933566/34281073-ccd18d5a-e681-11e7-8e4e-bc6bffc2928a.png)

Rebuilt, same training price.
![2017-12-21_19 05 30](https://user-images.githubusercontent.com/1933566/34281074-cce2ab58-e681-11e7-8b5f-d0b6b10ae02c.png)

**Comment by ataranlen** [comment]
I'm starting to suspect that this is unique to your server. This should fix it if the cause is what I think it is: https://github.com/ataranlen/civcraft/commit/cf2f6afb64fc6f57caeb2bd55460fc96e296045d

**Comment by TheLegionCrazy** [comment]
i've fixed it on my server long time ago, i checked commits and barracks same
build barracks, start train, train.... demolish an build on other town
