### ISSUE TITLE
Potential Exception in TradeGoodPreGenerate task.

### ISSUE THREAD

**Issue by TheLegionCrazy** [ataranlen/civcraft#160]
https://github.com/ataranlen/civcraft/blob/1.8-dev-1.11.2/civcraft/src/com/avrgaming/civcraft/populators/TradeGoodPreGenerate.java#L161

IllegalArgumentException if our list will be empty

**Comment by ataranlen** [comment]
If you're getting an exception here, the issue is elsewhere. The returned Trade good should never be nil.

Can you give any more info about how you got the exception? Did you update to the latest goodies.yml?

**Comment by TheLegionCrazy** [comment]
my bad. i forget about shrimps... at least 1 good with rarity 1 need
