### ISSUE TITLE
Potential typo with Wall&Road blocks (same #153)

### ISSUE THREAD

**Issue by TheLegionCrazy** [ataranlen/civcraft#161]
i fixed bug with structurechest, probably same typo in this objects
will check...

**Comment by TheLegionCrazy** [comment]
yeah...
`        HashSet<Wall> walls = wallChunks.get(coord);

        if (walls == null) {
            walls = new HashSet<>();
        }
        walls.remove(wall);
        wallChunks.put(coord, walls);`

maybe use
`        wallChunks.put(coord, null);`
we throwing if hashset will be non-null, instead empty
`if (CivGlobal.getWallChunk(chunkCoord) != null)`

**Comment by TheLegionCrazy** [comment]
npe

**Comment by ataranlen** [comment]
So is this just not an issue anymore?

**Comment by TheLegionCrazy** [comment]
issue.
Check not like this:
if (CivGlobal.getWallChunk(chunkCoord) != null)
throw...


check this: 
if (CivGlobal.getWallChunk(chunkCoord) != null && !CivGlobal.getWallChunk(chunkCoord).isEmpty())
throw...
