### ISSUE TITLE
CustomMobs mob's config makes server extremly laggy on large maps

### ISSUE THREAD

**Issue by realkarmakun** [ataranlen/civcraft#172]
https://pastebin.com/nqEVmPRf

After every message like this server is freezing for 10 or more seconds.
16000 world, 6GB RAM

More mobs = more lags on big maps.

Can we move on something like mythicMobs? It's not a problem create floating name + change exp like in Custom. Or maybe just change mobTypeName manually?

**Comment by TheLegionCrazy** [comment]
6gb is so low

**Comment by realkarmakun** [comment]
How much is fine?

**Comment by TheLegionCrazy** [comment]
![32bf455dec1853d3dad2a1c79b2903a6](https://user-images.githubusercontent.com/27031609/40938308-32ca307c-684a-11e8-9ab2-3d3a7b7a24f4.png) 2 servers
and what is your processor model?

**Comment by realkarmakun** [comment]
Well i guess there is no matching my VPS with VDS like this (64 GB! Big project i guess). But there is nothing i can do with just custommobs? Because it's only one thing that makes server freeze

**Comment by TheLegionCrazy** [comment]
don't use cm or make 3-4k map
ye, project is so big https://vimeworld.ru

**Comment by realkarmakun** [comment]
How i can turn it off? CivCraft is not starting without CM
