### ISSUE TITLE
Server lags

### ISSUE THREAD

**Issue by TheLegionCrazy** [ataranlen/civcraft#183]
Sooo.
I looked at some of the item components.
And I saw that you are using some shit line: player.updateInventory()

On updateInventory call it serializing many-many stacks:
![image](https://user-images.githubusercontent.com/27031609/52367466-3a4d9980-2a5d-11e9-8449-352d98081eba.png)
![image](https://user-images.githubusercontent.com/27031609/52367321-d9be5c80-2a5c-11e9-8ce8-5073687f6355.png)

Don't use it. Use: player.setItemInMainHand(player.getItemInMainHand());

For example, if 10 players will place War Camp, it'll create big lags

**Comment by ataranlen** [comment]
It would be better to link the actual lines in code, especially since Searching is disabled on forks on github.

**Comment by TheLegionCrazy** [comment]
https://github.com/ataranlen/civcraft/blob/1.8-dev/civcraft/src/com/avrgaming/civcraft/listener/CustomItemManager.java#L610 (most calls are here)
