### ISSUE TITLE
CivCraft 

### ISSUE THREAD

**Issue by LeonKlip** [ataranlen/civcraft#187]
How to change the encoding in the plugin?

**Comment by TheLegionCrazy** [comment]
you need to change the encoding in each yml file

**Comment by LeonKlip** [comment]
thank

**Comment by LeonKlip** [comment]
How to change?

**Comment by TheLegionCrazy** [comment]
in notepad

**Comment by LeonKlip** [comment]
Ok

**Comment by LeonKlip** [comment]
and one more question, all styles of architectures except the standard one don't work for me, how to connect them?

**Comment by TheLegionCrazy** [comment]
put ‘templates’ folder to your root server folder.
Example:
civcraft_server/templates

**Comment by LeonKlip** [comment]
this folder is there but nothing works

**Comment by LeonKlip** [comment]
How to connect themes to a plugin?

**Comment by LeonKlip** [comment]
How to put spawn?

**Comment by LeonKlip** [comment]
@TheLegionCrazy How to put spawn?

**Comment by ataranlen** [comment]
@LeonKlip This is abuse of the Issue system in github.
