### ISSUE TITLE
Error when trying add new sctucture or tech or wonder

### ISSUE THREAD

**Issue by ghost** [ataranlen/civcraft#47]
Hey,when im trying add new structure or tech or wonder i have that problem: https://gyazo.com/31dee75a9ead018fff144433eb8a89c5
Help please =)

**Comment by ataranlen** [comment]
Can you attach your yml files? It sounds like a formatting issue.

**Comment by ghost** [comment]
Techs and structures?(yml)
Add me on skype Egor.Kostyuk (TheLegion) will better in skype.
