### ISSUE TITLE
Quarry bug

### ISSUE THREAD

**Issue by merosoko** [ataranlen/civcraft#48]
The quarry is usung only wooden pickaxes, even if upgrade bought.

**Comment by ataranlen** [comment]
Is this on one of my servers? Is the quarry built by a different town that doesn't have the upgrade? Did you try putting only the diamond picks in? What version of the plugin are you running?

**Comment by ghost** [comment]
Last version minetexas civcraft,he upgrade quarry to 4 lvl(Medival style)
