### ISSUE TITLE
After add new wonder DB error

### ISSUE THREAD

**Issue by ghost** [ataranlen/civcraft#51]
Hey!When im added new wonder civ is on,but i have a mistake and i needed reload.Im reloaded server and again db error. 
https://gyazo.com/1e1e5b20ff126598ec886ffc50e67180

**Comment by ataranlen** [comment]
Can you pastebin your log file?

**Comment by ghost** [comment]
@ataranlen Archive or ctrl c ctrl v all log

**Comment by ataranlen** [comment]
http://pastebin.com/

**Comment by ghost** [comment]
@ataranlen 225k kb can't open it

**Comment by ataranlen** [comment]
Open the file in your text editor, copy all the text, and paste the text into pastebin and hit "create new paste"
