### ISSUE TITLE
After configurate new buff error(include logs and yaml)

### ISSUE THREAD

**Issue by ghost** [ataranlen/civcraft#53]
After configurate new buff https://gyazo.com/fa99bd5de0dac172e3f3e08b2725c978
Logs, wonders,techs,structures.yaml |
                                                          | 
                                                         \/

http://www.mediafire.com/download/g3ea1oskm22rytb/Ataranlen_12.08.16.zip

**Comment by ataranlen** [comment]
I'm attaching the files so anyone can reference them.

[latest.txt](https://github.com/ataranlen/civcraft/files/415850/latest.txt)
[structures.txt](https://github.com/ataranlen/civcraft/files/415851/structures.txt)
[techs.txt](https://github.com/ataranlen/civcraft/files/415853/techs.txt)
[wonders.txt](https://github.com/ataranlen/civcraft/files/415852/wonders.txt)
[buffs.txt](https://github.com/ataranlen/civcraft/files/415849/buffs.txt)

**Comment by ataranlen** [comment]
Please read up on YAML syntax before creating a new bug about config files.

https://github.com/Animosity/CraftIRC/wiki/Complete-idiot's-introduction-to-yaml
