### ISSUE TITLE
While building structures are making glass.Is x-ray.Need inctruction.

### ISSUE THREAD

**Issue by TheLegionDev** [ataranlen/civcraft#57]
Hello.
While building structure (for example: /build colosseum)
making big big glass,and when watching to glass,can see dia,gold e.t.c.
How to replace glass while building structure to for example iron block(42 id)

**Comment by ataranlen** [comment]
I'll make a config flag to change the block used.

I don't see this as a high priority as players wanting to use xray will do so anyways, with a lot more efficient add-ons.

**Comment by TheLegionDev** [comment]
@ataranlen now on bt this using: Valhalla;Azeroth.Azeroth going to win.Need fix it or its not white win.

**Comment by merosoko** [comment]
Is it possible today how to change it. on the same server as done, please tell me which file With this option, we can edit some of the lines in your source code :)
rip english

**Comment by merosoko** [comment]
rip english : )
