### ISSUE TITLE
1.8-dev enchanting issue

### ISSUE THREAD

**Issue by Hellcode48** [ataranlen/civcraft#60]
I have the option enabled for xp drops and enchanting enabled, when putting a enchant book and a pickaxe into a anvil, I cannot enchant the pickaxe, it just goes back into the anvil

**Comment by TheLegionDev** [comment]
In civcraft enchants only in library.

**Comment by ataranlen** [comment]
@TheLegionDev There is a newer config flag that is supposed to re-enable exp and enchanting.

@xH3LLRAIZ3Rx  I'll look into the books on the anvil. Are there any other issues you're having with enchanting?

**Comment by Hellcode48** [comment]
@ataranlen nothing else yet, have not tested enchanting via enchant table yet

**Comment by Hellcode48** [comment]
@ataranlen another issue: when dying with Keep Inventory on, your armor goes into the first 4 hotbar slots and deletes whatever was in those slots to begin with.

**Comment by Hellcode48** [comment]
@ataranlen ok when trying to enchant via enchanting table: ![Enchant error](http://i.imgur.com/FxOofAU.jpg)

**Comment by Hellcode48** [comment]
I can confirm that its working now :D
