### ISSUE TITLE
Compile error CivCraft's source code.

### ISSUE THREAD

**Issue by TheLegionDev** [ataranlen/civcraft#61]
Im trying to compile this(http://pastebin.com/3Jn1tJYh)
And have 35 errors ;/(http://pastebin.com/g7mCAK6z)
What i need do,and how you compiling your source code?

**Comment by tyggerr** [comment]
There might be multiple problems : 
1- Do you have all libraries?
2- Is your source folder setup correctly?
3- Are you able to code or do the errors appear only when you try to compile?
