### ISSUE TITLE
setShiny() for materials not showing

### ISSUE THREAD

**Issue by YourCoal** [ataranlen/civcraft#70]
As of 1.11, the NBT data in getShiny() to set an item's glowing effect broke, so the T1-T4 fish from materials.yml are no longer having their glowing effect around them.

https://github.com/ataranlen/civcraft/blob/1.8-dev/civcraft/src/gpl/AttributeUtil.java

```
public void setShiny() 

		if (nmsStack == null) {
			return;
		}
		
    	if (nmsStack.getTag() == null) {
    		nmsStack.setTag(new NBTTagCompound());
    	}
    	
    	NBTTagCompound enchCompound = nmsStack.getTag().getCompound("ench");
    	if (enchCompound == null) {
    		enchCompound = new NBTTagCompound();
    	}
    	
    	enchCompound.setShort("id", (short) 62); //Enchant id 62 = Lure
    	enchCompound.setShort("lvl", (short)1);
    	
    	nmsStack.getTag().set("ench", enchCompound);
    	this.setHideFlag(1);
	}
```

https://github.com/ataranlen/civcraft/blob/1.8-dev/civcraft/src/com/avrgaming/civcraft/lorestorage/LoreMaterial.java#L187

**Comment by ataranlen** [comment]
Do you have a potential solution for this already?

**Comment by YourCoal** [comment]
I tried something from spigot forums that suggests to edit the item metadata but that didn't work.

**Comment by YourCoal** [comment]
https://github.com/ataranlen/civcraft/commit/22a1fd87b7fa634f45f40ff8f31e291c6e5b585b fixes the issue.
