### ISSUE TITLE
Hooking into Vault-based economy plugins

### ISSUE THREAD

**Issue by Hellcode48** [ataranlen/civcraft#71]
I would love it if you can hook civcraft into vault-based economy plugins like essentials and Money Drop plugins for those who don't use the XP as Currency option

**Comment by Hellcode48** [comment]
then again, have not tested latest 1.11.2 build, so I will actually test to see if its fixed or not

**Comment by ataranlen** [comment]
I have not tested vault integration for other economy plugins.

**Comment by Hellcode48** [comment]
Sadly it doesn't work, I have Vault, and RPGMobMoney. the money drop, I pick it up, and nothing goes into the civcraft balance. Please add support

**Comment by Hellcode48** [comment]
@ataranlen I do think it would be fairly simple to hook into economy plugins, then again I am not a plugin developer, all I know is I could really use that economy hook so I can get started working on my server ;)

**Comment by ataranlen** [comment]
I've been working through the other higher priority bugs in the backlog. This one might get done, eventually.

**Comment by Hellcode48** [comment]
@ataranlen  Ok thank you, would it be possible if I could get someone to do it for you then do one of those github pull request things (not sure if its called that)?

**Comment by ataranlen** [comment]
If you can find someone willing to contribute such a change, feel free. Just make sure they understand they cannot break existing functionality in Civcraft or it will be rejected.

**Comment by Hellcode48** [comment]
@ataranlen alright, do you think it would be more plausible if I tell whoever to apply said change only if that config option is false for "Use XP Economy"?

**Comment by megamichiel** [comment]
Hello @ataranlen ,

While browsing through the project and adding required libraries, I found that some classes use NMS code specific to minecraft 1.8.8. Would it be ok if I change this to using reflection so it works on more versions?

**Comment by ataranlen** [comment]
That should be fine.

**Comment by Hellcode48** [comment]
@ataranlen megamichiel has submitted the pull request, tested the changes myself and I can say it works perfectly :D

**Comment by ataranlen** [comment]
The PR has been merged now. The next release will contain the fix.
