### ISSUE TITLE
Beetroots

### ISSUE THREAD

**Issue by YourCoal** [ataranlen/civcraft#74]
for v1.9+ you need to make bonemeal disabled on beetroots in BlockListener.java, and you should also add them to windmills too.

also for CivData.java, since you need to add in the ID for the beetroot crop, and I remember it being hard for me to find, I give this to you:

	public static final int BEETROOT_CROP = 207;

**Comment by ataranlen** [comment]
Beetroots don't have any current civcraft benefits.

**Comment by ataranlen** [comment]
Bonemeal is not disabled on Pumpkins or Melons, either.
