### ISSUE TITLE
Anticheat does not work in Minecraft 1.10+

### ISSUE THREAD

**Issue by YourCoal** [ataranlen/civcraft#78]
All players at war currently are unable to get on due to anti-cheat not being available, due to it being 1.8 still.

https://www.minetexas.com/minecraft-server-forum/showthread.php?tid=120

**Comment by ataranlen** [comment]
I'll see about adding some valid version identifiers into the config and check if they work.

**Comment by ataranlen** [comment]
Not sure if it is functional, but the same jar works with the latest forge and latest civcraft. Added new forge and optifine links in the thread you posted.
