### ISSUE TITLE
"Invalid horse" on stable horse.

### ISSUE THREAD

**Issue by TwilightVanish** [ataranlen/civcraft#89]
Simply clicked my Thoroughbred, poof gone, got this message:

![](https://i.gyazo.com/060fdc3d557303bf8b08ce8a155f6def.png)

**Comment by TwilightVanish** [comment]
Tried buying a new horse with the refund, took my money, didnt spawn a horse.

**Comment by ataranlen** [comment]
Seems there's a bigger issue at play, as you can't spawn in horses with "too much" health.

**Comment by YourCoal** [comment]
I have played for the last hour with some stuff, I have no fix, but it appears not being able to spawn Horses is a 1.11 thing, and it works fine in 1.10 and 1.10.2 versions.

**Comment by YourCoal** [comment]
Unless there is a completely new addition of an attribute saved to the horse, #108 is the fix I got.

**Comment by YourCoal** [comment]
I just found the error and will be making a pull request shortly, it has to do with NBT changes in 1.11.2.

**Comment by YourCoal** [comment]
I have created #123 which will fix the issue.

**Comment by ataranlen** [comment]
I have merged #123
